/*
 * SKELETONKEY — verification records table
 *
 * AUTO-GENERATED by tools/refresh-verifications.py from
 * docs/VERIFICATIONS.jsonl. Do not hand-edit; rerun the script.
 *
 * Source: tools/verify-vm/verify.sh appends one JSON record per
 * run; this generator dedupes to (module, vm_box, kernel, expect)
 * and keeps the latest by verified_at.
 */

#include "verifications.h"

#include <stddef.h>
#include <string.h>
#include <stdbool.h>

const struct verification_record verifications[] = {
    {
        .module        = "cgroup_release_agent",
        .verified_at   = "2026-05-23",
        .host_kernel   = "5.10.0-27-amd64",
        .host_distro   = "Debian GNU/Linux 11 (bullseye)",
        .vm_box        = "generic/debian11",
        .expect_detect = "VULNERABLE",
        .actual_detect = "VULNERABLE",
        .status        = "match",
    },
    {
        .module        = "dirty_pipe",
        .verified_at   = "2026-05-23",
        .host_kernel   = "5.15.0-91-generic",
        .host_distro   = "Ubuntu 22.04.3 LTS",
        .vm_box        = "generic/ubuntu2204",
        .expect_detect = "OK",
        .actual_detect = "OK",
        .status        = "match",
    },
    {
        .module        = "fuse_legacy",
        .verified_at   = "2026-05-23",
        .host_kernel   = "5.10.0-27-amd64",
        .host_distro   = "Debian GNU/Linux 11 (bullseye)",
        .vm_box        = "generic/debian11",
        .expect_detect = "VULNERABLE",
        .actual_detect = "VULNERABLE",
        .status        = "match",
    },
    {
        .module        = "netfilter_xtcompat",
        .verified_at   = "2026-05-23",
        .host_kernel   = "5.10.0-27-amd64",
        .host_distro   = "Debian GNU/Linux 11 (bullseye)",
        .vm_box        = "generic/debian11",
        .expect_detect = "VULNERABLE",
        .actual_detect = "VULNERABLE",
        .status        = "match",
    },
    {
        .module        = "pwnkit",
        .verified_at   = "2026-05-23",
        .host_kernel   = "5.4.0-169-generic",
        .host_distro   = "Ubuntu 20.04.6 LTS",
        .vm_box        = "generic/ubuntu2004",
        .expect_detect = "VULNERABLE",
        .actual_detect = "VULNERABLE",
        .status        = "match",
    },
};

const size_t verifications_count =
    sizeof(verifications) / sizeof(verifications[0]);

const struct verification_record *
verifications_for_module(const char *module, size_t *count_out)
{
    if (count_out) *count_out = 0;
    if (!module) return NULL;
    const struct verification_record *first = NULL;
    size_t n = 0;
    for (size_t i = 0; i < verifications_count; i++) {
        if (strcmp(verifications[i].module, module) == 0) {
            if (first == NULL) first = &verifications[i];
            n++;
        }
    }
    if (count_out) *count_out = n;
    return first;
}

bool verifications_module_has_match(const char *module)
{
    size_t n = 0;
    const struct verification_record *r = verifications_for_module(module, &n);
    for (size_t i = 0; i < n; i++)
        if (r[i].status && strcmp(r[i].status, "match") == 0)
            return true;
    return false;
}
